name: "github-dgs-build"
on: 
  workflow_dispatch:
    inputs:
      env-number:
        required: true
        type: choice
        options:
        - '1'
        - '2'
        - '3'
        - '4'
        description: "Environment to use (1 EKS / 2 SaaS / 3 Soleng / 4 Webinar)"
      fail-scan1:
        required: true
        type: boolean
        default: false
        description: "If true, will fail the build if watches violations are found during mvn scan"
      fail-scan2:
        required: true
        type: boolean
        default: false
        description: "If true, will fail the build if watches violations are found during build scan"
      maven-repo:
        required: true
        type: string
        default: "dro-backend-maven-virtual"
        description: "Maven virtual repository"
      docker-repo:
        required: true
        type: string
        default: "dro-backend-docker-dev-virtual"
        description: "Docker virtual repository"
      img-prefix:
        required: true
        type: choice
        options:
        - 'demo'
        - 'vuln'
        - 'hotfix'
        - 'fixed'
        description: "Environment to use (1 EKS / 2 SaaS / 3 Soleng / 4 Webinar)"        
      scan-mode:
        required: true
        type: choice
        options:
        - 'project'
        - 'watches'
        description: "scan mode to use for the maven jar "
      scan-context:
        required: false
        type: string
        default: "dro"
        description: "The watches list or the project key to use for the jar scan (for 'watches' its comma separated)"      
      project-key:
        required: false
        type: string
        default: "dro"
        description: "Jfrog project's key"      
jobs:
  build:
    runs-on: ubuntu-latest
    # Here we install all the tools : docker buildx, QEMU, JDK 11, JFrog CLI
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'        
          cache: 'maven'
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ENV_1: ${{ secrets[format('JF_SECRET_ENV_{0}', github.event.inputs.env-number)] }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "linux/amd64,linux/arm64"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # We build & test the JAR file, scan it and if scan result ok, we publish it to our artifactory maven repository
      - name: Run Maven JAR build 
        env:
          SCAN_OPTION: --${{ github.event.inputs.scan-mode }}=${{ github.event.inputs.scan-context }}
          MVN_VIRTUAL_REPO: ${{ github.event.inputs.maven-repo }}
          RT_DOCKER_REGISTRY: ${{ github.event.inputs.docker-repo }}
          PKG_VERSION: 1.${{ env.JFROG_CLI_BUILD_NUMBER }}.0
          JFROG_CLI_BUILD_PROJECT: ${{ github.event.inputs.project-key }}
        run: |
          # Collect environment variables for the build
          jf rt bce ${{ env.JFROG_CLI_BUILD_NAME }}-jar ${{ env.JFROG_CLI_BUILD_NUMBER }} 
          echo '== mvn config =='
          jf mvnc --repo-resolve-releases=${{ env.MVN_VIRTUAL_REPO }} \
            --repo-deploy-releases=${{ env.MVN_VIRTUAL_REPO }} \
            --repo-resolve-snapshots=${{ env.MVN_VIRTUAL_REPO }} \
            --repo-deploy-snapshots=${{ env.MVN_VIRTUAL_REPO }}
          echo '== maven jar build =='
          jf mvn --build-name=${{ env.JFROG_CLI_BUILD_NAME }}-jar -Drevision=1.${{ env.JFROG_CLI_BUILD_NUMBER }}.0 --build-number=${{ env.JFROG_CLI_BUILD_NUMBER }} -Dmaven.test.skip=true clean package
          # collect vcs info
          jf rt bag ${{ env.JFROG_CLI_BUILD_NAME }}-jar ${{ env.JFROG_CLI_BUILD_NUMBER }}
      - name: Xray on-demand scan of JAR 
        env:
          SCAN_OPTION: --${{ github.event.inputs.scan-mode }}=${{ github.event.inputs.scan-context }}
          MVN_VIRTUAL_REPO: ${{ github.event.inputs.maven-repo }}
          RT_DOCKER_REGISTRY: ${{ github.event.inputs.docker-repo }}
          PKG_VERSION: 1.${{ env.JFROG_CLI_BUILD_NUMBER }}.0
          JFROG_CLI_BUILD_PROJECT: ${{ github.event.inputs.project-key }}
        run: |          
          echo 'running xray on demand scan'
          # Xray on demand scan example
          jf scan ./target/dgs-skeleton-${{ env.PKG_VERSION }}.jar --fail=${{ github.event.inputs.fail-scan1 }}
      - name: Publish JAR & Build Info 
        env:
          SCAN_OPTION: --${{ github.event.inputs.scan-mode }}=${{ github.event.inputs.scan-context }}
          MVN_VIRTUAL_REPO: ${{ github.event.inputs.maven-repo }}
          RT_DOCKER_REGISTRY: ${{ github.event.inputs.docker-repo }}
          PKG_VERSION: 1.${{ env.JFROG_CLI_BUILD_NUMBER }}.0
          JFROG_CLI_BUILD_PROJECT: ${{ github.event.inputs.project-key }}
        run: |          
          # if scan is ok publish the jar
          jf mvn -Dmaven.test.skip=true -Drevision=1.${{ env.JFROG_CLI_BUILD_NUMBER }}.0 --build-name=${{ env.JFROG_CLI_BUILD_NAME }}-jar --build-number=${{ env.JFROG_CLI_BUILD_NUMBER }} deploy
          # Publish build info
          echo '== publish maven artifacts build infos =='
          jf rt bp ${{ env.JFROG_CLI_BUILD_NAME }}-jar ${{ env.JFROG_CLI_BUILD_NUMBER }}
         
      # Now multi arch docker build for our maven application
      # JFrog docker multi arch resources : 
      # https://jfrog.com/blog/the-more-the-merrier-multi-arch-docker-manifests-with-buildx-and-artifactory/
      # https://jfrog.com/knowledge-base/artifactory-how-to-use-jfrog-cli-to-add-build-info-to-images-built-with-docker-buildx/
      - name: Login to Artifactory Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets[format('JF_HOST_{0}', github.event.inputs.env-number)] }}
          username: ${{ secrets[format('JF_LOGIN_{0}', github.event.inputs.env-number)] }}
          password: ${{ secrets[format('JF_PWD_{0}', github.event.inputs.env-number)] }}
      - name: Build and push docker SpringBoot's jar based docker images
        env: 
          PKG_VERSION: 1.${{ env.JFROG_CLI_BUILD_NUMBER }}.0
          JFROG_CLI_BUILD_PROJECT: ${{ github.event.inputs.project-key }}
          RT_REPO_PREFIX: ${{ secrets[format('JF_HOST_{0}', github.event.inputs.env-number)] }}/${{ github.event.inputs.docker-repo }}/
        uses: docker/build-push-action@v3
        id: docker_build_1
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          outputs: |
            type=image
          build-args: |
            JAR_FILE_NAME=dgs-skeleton-${{ env.PKG_VERSION }}.jar
            RT_REPO_PREFIX=${{ env.RT_REPO_PREFIX }}
          tags: ${{ secrets[format('JF_HOST_{0}', github.event.inputs.env-number)] }}/${{ github.event.inputs.docker-repo }}/multiarch/${{ github.event.inputs.img-prefix }}-dgs:${{ env.PKG_VERSION }}
      - name: Run Maven WAR build 
        env:
          MVN_VIRTUAL_REPO: ${{ github.event.inputs.maven-repo }}
          RT_DOCKER_REGISTRY: ${{ github.event.inputs.docker-repo }}
          PKG_TYPE: war
          PKG_VERSION: 1.${{ env.JFROG_CLI_BUILD_NUMBER }}.0
        run: |
          # Collect environment variables for the build
          jf rt bce ${{ env.JFROG_CLI_BUILD_NAME }}-war ${{ env.JFROG_CLI_BUILD_NUMBER }} 
          jf mvnc --repo-resolve-releases=${{ env.MVN_VIRTUAL_REPO }} \
            --repo-deploy-releases=${{ env.MVN_VIRTUAL_REPO }} \
            --repo-resolve-snapshots=${{ env.MVN_VIRTUAL_REPO }} \
            --repo-deploy-snapshots=${{ env.MVN_VIRTUAL_REPO }}
          jf rt bag ${{ env.JFROG_CLI_BUILD_NAME }}-war ${{ env.JFROG_CLI_BUILD_NUMBER }} 
          jf mvn -f pom-war.xml -Drevision=1.${{ env.JFROG_CLI_BUILD_NUMBER }}.0 -Dmaven.test.skip=true clean package
          jf mvn -f pom-war.xml -Drevision=1.${{ env.JFROG_CLI_BUILD_NUMBER }}.0 -Dmaven.test.skip=true --build-name=${{ env.JFROG_CLI_BUILD_NAME }}-war --build-number=${{ env.JFROG_CLI_BUILD_NUMBER }} deploy
          # Publish build info
          jf rt bp ${{ env.JFROG_CLI_BUILD_NAME }}-war ${{ env.JFROG_CLI_BUILD_NUMBER }}
      - name: Build and push docker tomcat + war based docker images
        env: 
          PKG_VERSION: 1.${{ env.JFROG_CLI_BUILD_NUMBER }}.0
          JFROG_CLI_BUILD_PROJECT: ${{ github.event.inputs.project-key }}
          RT_REPO_PREFIX: ${{ secrets[format('JF_HOST_{0}', github.event.inputs.env-number)] }}/${{ github.event.inputs.docker-repo }}/
        uses: docker/build-push-action@v3
        id: docker_build_2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./DockerfileTomcat
          push: true
          outputs: |
            type=image
          build-args: |
            WAR_FILE_NAME=dgs-skeleton-webapp-${{ env.PKG_VERSION }}.war
            RT_REPO_PREFIX=${{ env.RT_REPO_PREFIX }}
          tags: ${{ secrets[format('JF_HOST_{0}', github.event.inputs.env-number)] }}/${{ github.event.inputs.docker-repo }}/multiarch/${{ github.event.inputs.img-prefix }}-dgs-tcat:${{ env.PKG_VERSION }}
          
      - name: Scan & push Docker build info
        env:
          PKG_VERSION: 1.${{ env.JFROG_CLI_BUILD_NUMBER }}.0
          JFROG_CLI_BUILD_PROJECT: ${{ github.event.inputs.project-key }}
          RT_DOCKER_HOST: ${{ secrets[format('JF_HOST_{0}', github.event.inputs.env-number)] }}
          RT_REPO_PREFIX: ${{ secrets[format('JF_HOST_{0}', github.event.inputs.env-number)] }}/${{ github.event.inputs.docker-repo }}/
        run: |
          echo ${{ secrets[format('JF_HOST_{0}', github.event.inputs.env-number)] }}/${{ github.event.inputs.docker-repo }}/multiarch/${{ github.event.inputs.img-prefix }}-dgs:${{ env.PKG_VERSION }}@${{ steps.docker_build_1.outputs.ImageID }} > ./image-file-details-1.txt
          echo ${{ secrets[format('JF_HOST_{0}', github.event.inputs.env-number)] }}/${{ github.event.inputs.docker-repo }}/multiarch/${{ github.event.inputs.img-prefix }}-dgs-tcat:${{ env.PKG_VERSION }}@${{ steps.docker_build_2.outputs.ImageID }} > ./image-file-details-2.txt
          # Collect environment variables for the build
          jf rt bce ${{ env.JFROG_CLI_BUILD_NAME }}-docker ${{ env.JFROG_CLI_BUILD_NUMBER }} 
          # collect vcs info
          jf rt bag ${{ env.JFROG_CLI_BUILD_NAME }}-docker ${{ env.JFROG_CLI_BUILD_NUMBER }}
          # As the docker images have been built by buildx, we don't have them locally, 
          # so we link the build info to the already published images in previous steps
          jf rt bdc ${{ github.event.inputs.docker-repo }} --image-file ./image-file-details-1.txt --build-name ${{ env.JFROG_CLI_BUILD_NAME }}-docker --build-number ${{ env.JFROG_CLI_BUILD_NUMBER }}
          jf rt bdc ${{ github.event.inputs.docker-repo }} --image-file ./image-file-details-2.txt --build-name ${{ env.JFROG_CLI_BUILD_NAME }}-docker --build-number ${{ env.JFROG_CLI_BUILD_NUMBER }}
          # Publish build info
          jf rt bp ${{ env.JFROG_CLI_BUILD_NAME }}-docker ${{ env.JFROG_CLI_BUILD_NUMBER }}
          # Xray build scan example
          jf bs --fail=${{ github.event.inputs.fail-scan2 }} ${{ env.JFROG_CLI_BUILD_NAME }}-docker ${{ env.JFROG_CLI_BUILD_NUMBER }}
          # Tag release with extra properties
          jf rt sp "drobundle.status=ok;drobundle.version=1.${{ env.JFROG_CLI_BUILD_NUMBER }}" --spec tagspecs.json --spec-vars="dockerRepo=${{ github.event.inputs.docker-repo }};imgPrefix=multiarch/${{ github.event.inputs.img-prefix }}-dgs;buildName=${{ env.JFROG_CLI_BUILD_NAME }}-docker;buildNumber=${{ env.JFROG_CLI_BUILD_NUMBER }}"

